# Generated by Django 4.0 on 2021-12-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desenvolvedora',
            options={'verbose_name_plural': 'desenvolvedoras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'gêneros'},
        ),
        migrations.AlterModelOptions(
            name='plataforma',
            options={'verbose_name_plural': 'plataformas'},
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='')),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('desenvolvedora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.desenvolvedora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.genero')),
            ],
            options={
                'verbose_name_plural': 'jogos',
            },
        ),
    ]
