# Generated by Django 4.0 on 2021-12-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_desenvolvedora_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.ManyToManyField(related_name='jogos', to='core.Plataforma'),
        ),
    ]
