# Generated by Django 4.0 on 2021-12-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_itenscompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedora',
            name='logotipo',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='imagem',
        ),
    ]
